apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-experiment
spec:
  completions: 1000
  completionMode: Indexed
  parallelism: 1
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: producer
          image: my-kafka-producer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
          envFrom:
            - configMapRef:
                name: producer-config
          volumeMounts:
            - name: profiles
              mountPath: /profiles
      volumes:
        - name: profiles
          hostPath:
            path: /tmp/kafka-profiles
            type: DirectoryOrCreate
