apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: my-cluster
spec:
  resources:
    requests: # 0.25 코어, 2GB 메모리
      cpu: "250m"
      memory: "2Gi"
    limits:
      cpu: "250m" 
      memory: "2Gi"
  jvmOptions: # JVM Heap 옵션 1GB 메모리
    -Xms: 1g
    -Xmx: 1g
  replicas: 1
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: my-cluster
spec:
  resources:
    requests: # 0.5 코어, 2GB 메모리
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"
  jvmOptions: # JVM Heap 옵션 1GB 메모리
    -Xms: 1g
    -Xmx: 1g
  replicas: 1
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.1.1
    metadataVersion: 4.1-IV0
    config:
      auto.create.topics.enable: true
      message.max.bytes: 15728640
      replica.fetch.max.bytes: 15728640
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true

  # entityOperator:
  #   topicOperator:
  #     resources:
  #       requests:
  #         cpu: "100m"
  #         memory: "512Mi"
  #       limits:
  #         cpu: "100m"
  #         memory: "512Mi"
  #     jvmOptions:
  #       -Xms: 256m
  #       -Xmx: 256m
  #   userOperator:
  #     resources:
  #       requests:
  #         cpu: "100m"
  #         memory: "512Mi"
  #       limits:
  #         cpu: "100m"
  #         memory: "512Mi"
  #     jvmOptions:
  #       -Xms: 256m
  #       -Xmx: 256m


